$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        320:{
            items:2
        },
        375:{
            items:3
        },
        425:{
            items:2
        },
        768:{
            items:4
        },
        1024:{
            items:5
        },
        1440:{
            items:7
        },
        2560:{
            items:12
        },
        900:{
            items:5
        },
        820:{
            items:4
        },
        280:{
            items:4
        },
        1280:{
            items:6
        },
        414:{
            items:3
        }
    }
})